export const REQUEST_BOOKS='REQUEST_BOOKS'
export const GET_BOOKS_FAILURE='GET_BOOKS_FAILURE'
export const GET_BOOKS_SUCCESS='GET_BOOKS_SUCCESS'

export const TOGGLE_BOOK_FORM_SHOWING = 'TOGGLE_BOOK_FORM_SHOWING'
export const TOGGLE_BOOK_RESULTS_SHOWING = 'TOGGLE_BOOK_RESULTS_SHOWING'